### ISSUE TITLE
Lien d'invitation invalide

### ISSUE THREAD

**Issue by KaKi87** [NaN42/discussions-live#2]
Bonjour,

Serait-il possible d'avoir un nouveau lien ? xD

Merci ;)

**Comment by SirLynix** [comment]
Le lien d'invitation est pourtant toujours valide. Quel est ton nom et tag
sur Discord ?

**Comment by KaKi87** [comment]
![2018-08-30 12_28_55-discord](https://user-images.githubusercontent.com/21284089/44846343-5cdabb80-ac50-11e8-8a06-b085fa6a7e9d.png)

Le lien que j'ai utilisé : https://discordapp.com/invite/zcWp9sC

Mon profil Discord est KaKi87#2368, merci.

**Comment by SirLynix** [comment]
Je confirme que le lien d'invitation est valide, ce qui signifie que tu dois être banni du serveur.

Et effectivement après avoir regardé la table des bannissements ton compte en fait partie.

Après recherche dans l'historique, ton bannissement est dû à ton comportement juste avant le bannissement en question, où tu insultes un administrateur avant de dire que tu vas de toute façon quitter la communauté et poster un lien d'invitation pour une autre communauté (ce qui est contre le règlement du serveur de façon assez claire).

Voilà voilà.

**Comment by KaKi87** [comment]
Pourquoi avais-je insulté l'administrateur, et pourquoi étais-je parti ?

**Comment by SirLynix** [comment]
Une histoire d'avion et de trains, malheureusement le bannissement a effacé les derniers messages donc je ne peux pas te fournir plus de détails.

Après personnellement je trouve qu'on fait trop de bannissements permanents sur NaN (d'ailleurs le nouveau bot fait par défaut des bannissements temporaires), je vais donc débannir ton compte, on verra bien comment ça se passe.

**Comment by KaKi87** [comment]
D'accord je reviens.
